function shorten = shortenFilename(str)
%SHORTENFILENAME Summary of this function goes here
%   Detailed explanation goes here

shorten = strcat( ...
    str(1:10), ...
    ' ... ', ...
    str(end-15:end) ...
);

end

